<a href="https://colab.research.google.com/github/practice-grounds-wpaarth24/NLP/blob/main/NLP_NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

--2024-10-24 04:23:02--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.167.207, 142.251.179.207, 64.233.180.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.167.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.006s  

2024-10-24 04:23:02 (99.3 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [2]:
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/refs/heads/main/extras/helper_functions.py

--2024-10-24 04:23:04--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/refs/heads/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2024-10-24 04:23:04 (66.0 MB/s) - ‘helper_functions.py’ saved [10246/10246]



In [3]:
import zipfile
zip_ref = zipfile.ZipFile("nlp_getting_started.zip")
zip_ref.extractall()
zip_ref.close()

In [4]:
import pandas as pd
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [5]:
train_df_shuffled = train_df.sample(frac=1, random_state=42)
train_df_shuffled.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [6]:
from sklearn.model_selection import train_test_split
train_sentences, val_sentences, train_labels, val_labels = train_test_split(train_df_shuffled["text"].to_numpy(),
                                                                            train_df_shuffled["target"].to_numpy(),
                                                                            test_size=0.2,
                                                                            random_state=42)

In [7]:
from os.path import split
import tensorflow as tf

from tensorflow.keras.layers import TextVectorization


text_vectorizer = TextVectorization(max_tokens=10000,
                                    standardize = "lower_and_strip_punctuation",
                                    split = "whitespace",
                                    ngrams = None,
                                    output_mode = "int",
                                    output_sequence_length = None,
                                    pad_to_max_tokens=True
                                    )

In [8]:
text_vectorizer.adapt(train_sentences)

In [9]:
sample_sentence = "DJ Sanghvi College of Engineering"
sample_for_embedding = text_vectorizer([sample_sentence])

In [10]:
words_number = text_vectorizer.get_vocabulary()
words_number[:10]

['', '[UNK]', 'the', 'a', 'in', 'to', 'of', 'and', 'i', 'is']

#**Embedding**

In [12]:
import tensorflow as tf
max_length = 15
Embedding = tf.keras.layers.Embedding(input_dim = 10000,
                                              output_dim = 128,
                                              input_length = max_length)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
embed = Embedding(sample_for_embedding)
embed

<tf.Tensor: shape=(1, 5, 128), dtype=float32, numpy=
array([[[ 4.92846258e-02,  4.07630838e-02,  3.21744420e-02,
          3.90107557e-03, -4.05243151e-02, -1.05831251e-02,
          3.98442782e-02, -5.00509888e-03,  4.56028841e-02,
          2.75892951e-02, -3.13189626e-02,  1.93601586e-02,
         -2.58252770e-03, -2.71005034e-02,  1.38344653e-02,
          3.00908089e-03, -3.65904681e-02, -3.64785679e-02,
         -7.08987564e-03,  5.56762144e-03, -1.15507357e-02,
          2.15859078e-02,  1.61806606e-02, -3.31191421e-02,
         -2.02525854e-02,  3.00284661e-02,  3.06960195e-03,
          3.22048925e-02,  2.29637660e-02, -1.43276937e-02,
         -3.17591429e-02, -4.23737653e-02,  4.99755479e-02,
         -1.07224211e-02,  3.22710983e-02,  1.06729567e-04,
         -4.90283743e-02, -3.86039391e-02, -1.24110952e-02,
         -4.36005108e-02,  3.92577760e-02, -4.09602746e-02,
          1.04842782e-02, -3.81175876e-02,  5.03589958e-03,
         -3.94977629e-04,  1.44733526e-02, -2.4

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

In [26]:
from sklearn.model_selection import GridSearchCV

Naive_model = Pipeline([('tfidf', TfidfVectorizer()), ('nb', MultinomialNB())])

param_grid = {
    'tfidf__max_df': [0.7, 0.8, 0.9,0.5],
    'tfidf__min_df': [2, 5, 10],
    'nb__alpha': [0.1, 1.0, 10.0,0.01]
}

grid_search = GridSearchCV(Naive_model, param_grid, cv=10, scoring='accuracy')

grid_search.fit(train_sentences, train_labels)

print("Best parameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)

Best parameters: {'nb__alpha': 1.0, 'tfidf__max_df': 0.7, 'tfidf__min_df': 5}
Best score: 0.80311986863711


In [27]:
val_predictions = grid_search.predict(val_sentences)

In [29]:
from sklearn.metrics import accuracy_score, precision_score
accuracy_score(val_labels, val_predictions) * 100, precision_score(val_labels, val_predictions) * 100

(79.84241628365069, 85.23622047244095)

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(val_labels, val_predictions)

array([[783,  75],
       [232, 433]])

In [32]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [33]:
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered_words)

In [34]:
train_sentences_no_stopwords = [remove_stopwords(sentence) for sentence in train_sentences]
val_sentences_no_stopwords = [remove_stopwords(sentence) for sentence in val_sentences]

In [35]:

Naive_model_2 = Pipeline([('tfidf', TfidfVectorizer()), ('nb', MultinomialNB())])

param_grid = {
    'tfidf__max_df': [0.7, 0.8, 0.9,0.5],
    'tfidf__min_df': [2, 5, 10],
    'nb__alpha': [0.1, 1.0, 10.0,0.01]
}

grid_search = GridSearchCV(Naive_model_2, param_grid, cv=10, scoring='accuracy')

grid_search.fit(train_sentences_no_stopwords, train_labels)

print("Best parameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)

Best parameters: {'nb__alpha': 1.0, 'tfidf__max_df': 0.5, 'tfidf__min_df': 2}
Best score: 0.8044334975369457


In [36]:
from sklearn.metrics import accuracy_score, precision_score
val_predictions = grid_search.predict(val_sentences_no_stopwords)
accuracy_score(val_labels, val_predictions) * 100, precision_score(val_labels, val_predictions) * 100

(79.84241628365069, 83.90151515151516)